a = eval(input("Informe um valor para A: "))
b = eval(input("Informe um valor para B: "))
print(f"Resultado da adição:  {a + b}")
print(f"Resultado da subtração: {a - b}")
print(f"Resultado da multiplicação: {a * b}")
print(f"Resultado da divisão: {a / b}")